- name: Asegurarme que el puerto queda abierto en mi máquina redhat
  firewalld:
    port: "{{ puerto }}/{{ protocolo }}"
    permanent: true
    state: enabled
  become: True # Ponte como superusuario / administrador
