
- name: Asegurarme que el puerto queda abierto en mi máquina Windows
  win_firewall_rule:
        name:       "{{ nombre }}"
        localport:  "{{ puerto }}"
        action:     allow
        direction:  in
        protocol:   "{{ protocolo }}"
        state:      present
        enabled:    yes