- name: Obtener el sistema operativo de la máquina
  setup:
    gather_subset:
      - distribution
      - os_family
  when: >
     ansible_facts.distribution is undefined or ansible_facts.os_family is undefined


- name: Cortar la ejecución del playbook
  meta: end_host
  when: > 
      (     ansible_facts.os_family    not in sistemasOperativosAdmitidos.familias 
        and ansible_facts.distribution not in sistemasOperativosAdmitidos.distribuciones )
      or puerto is undefined


- name: Abrir el puerto
  include_tasks:
    file: >-
              os/{{ (ansible_facts.os_family 
                    if ansible_facts.os_family in sistemasOperativosAdmitidos.familias 
                    else ansible_facts.distribution) | lower }}.yaml
