- name: Cortar la ejecución del playbook
  when: puerto is undefined # Si no me han dado un puerto
  
- name: Obtener el sistema operativo de la máquina

- name: Asegurarme que el puerto queda abierto
  win_firewall_rule:
        name:       "{{ nombre }}"
        localport:  "{{ puerto }}"
        action:     allow
        direction:  in
        protocol:   "{{ protocolo }}"
        state:      present
        enabled:    yes
  when: ansible_facts.distribution == 'Windows' # Si tengo una máquina windows

- name: Asegurarme que el puerto queda abierto si tengo una máquina ubuntu
  when: ansible_facts.distribution == 'Ubuntu' # Si tengo una máquina ubuntu

- name: Asegurarme que el puerto queda abierto si tengo una máquina redhat
  when: ansible_facts.distribution == 'Redhat' # Si tengo una máquina redhat

- name: Cortar la ejecución del playbook
  when: 
    - ansible_facts.distribution != 'Windows' #Si tengo una máquina desconocida
    - ansible_facts.distribution != 'Ubuntu'
    - ansible_facts.distribution != 'Redhat'
    